# ===========================
# miskaa's AntiVPN Configuration
# ===========================
enabled: true
countryCheckEnabled: false

whitelistedCountries: []

# ========= MESSAGES ===========
vpnMessage: "&cYou're using a VPN or a Proxy which isn't allowed!"
countryMessage: "&cYour country is not allowed on this server!"
ipBanMessage: "&cYou have been banned for repeated failed join attempts!"
